version: '3.8'
services:
  ui:
    build:
      context: ./UI
      dockerfile: DockerFile
    ports:
      - "8081:8081"
    volumes:
      - /UI/templates:/templates
      - /UI/static:/static
  engine:
    build: 
      context: ./Engine
      dockerfile: DockerFile
    ports:
      - "8082:8081"