FROM python

WORKDIR /app

COPY engine.py /app

COPY commands.py /app

COPY database_manager.py /app

COPY requirements.txt /app

COPY data /app/data

RUN pip install -r requirements.txt

CMD ["flask","--app","engine","--debug","run","--host=0.0.0.0","--port","8081"]