FROM python

WORKDIR /app

COPY engine.py /app

COPY models.py /app

COPY user_operations.py /app

COPY account_operations.py /app

COPY schemas.py /app

COPY requirements.txt /app

COPY instance /app/instance

RUN pip install -r requirements.txt

CMD ["flask","--app","engine","--debug","run","--host=0.0.0.0","--port","8081"]