FROM python

WORKDIR /app

COPY engine.py /app

COPY models.py /app

COPY user_operations.py /app

COPY account_operations.py /app

COPY transaction_operations.py /app

COPY schemas.py /app

COPY requirements.txt /app

COPY instance /app/instance

RUN pip install -r requirements.txt

CMD ["python", "engine.py"]